#!/usr/bin/env ruby

MIN_COMMIT_LENGTH = 20
PREFIX = "#"

PREFIX_LOW = PREFIX.downcase

$currentBranch = `git rev-parse --abbrev-ref HEAD`
$commitFileName = ARGV[0]

def checkTicketNumbers(branch, commit)
	if branch != commit
		puts "Ticket number of commit does not match the branch name (#{commit} != #{branch})"
		exit 1
	end
end

def rewriteCommitMsg(lines, ticketNumber, commitMsg)
	newCommitMsg = "[#{PREFIX}#{ticketNumber}] #{commitMsg}"
	lines[0] = newCommitMsg
	newFileContents = lines.join("")
	IO.write $commitFileName, newFileContents
	puts "Commit message corrected to: '#{newCommitMsg.delete("\n")}'"
end

if /(?:#{PREFIX}|#{PREFIX_LOW})(\d+)-.+/ =~ $currentBranch
	# Branch name does start with ticket number, check commit message
	branchTicketNumber = $1 # Ticket number from branch
	
	commitFileLines = IO.readlines($commitFileName)
	commitMessage = commitFileLines[0]

	unless commitMessage.start_with?("Merge")
		# Check if commit message starts with valid ticket number and commit is > 20 chars
		if /\[#{PREFIX}(\d+)\] .{#{MIN_COMMIT_LENGTH},}$/ =~ commitMessage
			# Commit message does match the format, check the ticket numbers match and error if not
			checkTicketNumbers($1, branchTicketNumber)
		else
			# Commit message does not match the format
			# If the prefix is in lowercase or there are extra spaces, we can correct it
			if /\[(?:#{PREFIX}|#{PREFIX_LOW})(\d+)\] *(.{#{MIN_COMMIT_LENGTH},})$/ =~ commitMessage
				checkTicketNumbers($1, branchTicketNumber)

				rewriteCommitMsg(commitFileLines, $1, $2)
			else
				if commitMessage.length < MIN_COMMIT_LENGTH
					# Commit message too short, error..
					puts "Commit message must be > #{MIN_COMMIT_LENGTH} chars"
					exit 1
				end
				rewriteCommitMsg(commitFileLines, branchTicketNumber, commitMessage)
			end
		end
	end
end
